# Site settings
title:          Swiftier
description:    "A tale of swift performance"
url:            "https://swiftier.co"

# Google Analytics
google_analytics: UA-149474631-1

# Author
author:
  name:         Siddharth Gupta
  url:          https://siddharth.work
  email:        sids@outlook.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       8

# Excludes
exclude: [ Gemfile, Gemfile.lock ]
